python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/oa_lrc_linear': [Errno 2] No such file or directory
python: can't open file '/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/pa_lrc_linear': [Errno 2] No such file or directory
goemotions
3
Traceback (most recent call last):
  File "/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/pa_linear_model_large.py", line 213, in <module>
    main(args)
  File "/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/pa_linear_model_large.py", line 107, in main
    model = Linear(configs).to(configs['device'])
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

goemotions
3
Traceback (most recent call last):
  File "/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/pa_linear_model_large.py", line 213, in <module>
    main(args)
  File "/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/pa_linear_model_large.py", line 107, in main
    model = Linear(configs).to(configs['device'])
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

goemotions
3
Traceback (most recent call last):
  File "/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/pa_linear_model_large.py", line 213, in <module>
    main(args)
  File "/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/pa_linear_model_large.py", line 107, in main
    model = Linear(configs).to(configs['device'])
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

goemotions
3
Traceback (most recent call last):
  File "/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/pa_linear_model_large.py", line 213, in <module>
    main(args)
  File "/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/pa_linear_model_large.py", line 107, in main
    model = Linear(configs).to(configs['device'])
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

goemotions
3
Traceback (most recent call last):
  File "/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/pa_linear_model_large.py", line 213, in <module>
    main(args)
  File "/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/pa_linear_model_large.py", line 107, in main
    model = Linear(configs).to(configs['device'])
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

goemotions
3
Traceback (most recent call last):
  File "/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/pa_linear_model_large.py", line 213, in <module>
    main(args)
  File "/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/pa_linear_model_large.py", line 107, in main
    model = Linear(configs).to(configs['device'])
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

goemotions
3
Traceback (most recent call last):
  File "/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/pa_linear_model_large.py", line 213, in <module>
    main(args)
  File "/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/pa_linear_model_large.py", line 107, in main
    model = Linear(configs).to(configs['device'])
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

goemotions
3
Traceback (most recent call last):
  File "/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/pa_linear_model_large.py", line 213, in <module>
    main(args)
  File "/data/shaoxiao/Desktop/Multi-graph concentration resources/macro-auc-pytorch-main/pa_linear_model_large.py", line 107, in main
    model = Linear(configs).to(configs['device'])
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/public/anaconda/anaconda/envs/macro-auc-theory1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

